### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by etam89** [secworks/sha3#2]
Warning-[TFIPC] Too few instance port connections
sha3.v, 152
"sha3_core core( .clk (clk),  .reset_n (reset_n),  .init (core_init),  .next (core_next),  .mode (core_mode),  .block (core_block),  .ready (core_ready),  .digest (core_digest),  .digest_valid (core_digest_valid));"
  The above instance has fewer port connections than the module definition.
  Please use '+lint=TFIPC-L' to print out detailed information of unconnected 
  ports.

**Comment by secworks** [comment]
Aloha!

Please look at the top of the readme regarding the status:

Status
Not completed. Does not work. Do. Not. Use.

This core is far from completed. It will not lint correctly.
